// Bellingham Live Music Events Data
// Last updated: [Current Date]

const eventsData = [
    { id: "BEL025", title: "Booker T. Jones: Over 60 Years of Soul", date: "2025-10-02", time: "7:30 PM", venue: "Mount Baker Theatre", address: "104 N Commercial St", lat: 48.7545, lng: -122.4787, price: "$45", age_limit: "All Ages", genre: "Soul/R&B", ticket_url: "https://mountbakertheatre.com", event_url: "https://mountbakertheatre.com", description: "Legendary Stax Records musician and Booker T. & the M.G.'s keyboardist" },
    { id: "BEL026", title: "Bellingham Symphony: Beethoven's Ode to Joy", date: "2025-10-04", time: "7:30 PM", venue: "Mount Baker Theatre", address: "104 N Commercial St", lat: 48.7545, lng: -122.4787, price: "$35", age_limit: "All Ages", genre: "Classical", ticket_url: "https://bellinghamsymphony.org", event_url: "https://bellinghamsymphony.org", description: "BSO performs Beethoven's iconic 9th Symphony" },
    { id: "BEL027", title: "BSO: Beethoven's Ode to Joy", date: "2025-10-05", time: "2:00 PM", venue: "Mount Baker Theatre", address: "104 N Commercial St", lat: 48.7545, lng: -122.4787, price: "$35", age_limit: "All Ages", genre: "Classical", ticket_url: "https://bellinghamsymphony.org", event_url: "https://bellinghamsymphony.org", description: "Second performance of Beethoven's 9th Symphony" },
    { id: "BEL028", title: "Bellingham Exit Festival - Final Year", date: "2025-10-08", time: "6:00 PM", venue: "Downtown Bellingham", address: "Various Venues", lat: 48.7544, lng: -122.4783, price: "$30", age_limit: "All Ages", genre: "Multi-Genre", ticket_url: "https://exitfestival.com", event_url: "https://exitfestival.com", description: "Final year of Bellingham's premier music festival" },
    { id: "BEL029", title: "I'm With Her", date: "2025-10-09", time: "8:00 PM", venue: "Mount Baker Theatre", address: "104 N Commercial St", lat: 48.7545, lng: -122.4787, price: "$55", age_limit: "All Ages", genre: "Folk", ticket_url: "https://mountbakertheatre.com", event_url: "https://mountbakertheatre.com", description: "Grammy-winning folk supergroup featuring Sara Watkins, Sarah Jarosz, and Aoife O'Donovan" },
    { id: "BEL030", title: "Demetri Martin", date: "2025-10-10", time: "7:00 PM", venue: "Mount Baker Theatre", address: "104 N Commercial St", lat: 48.7545, lng: -122.4787, price: "$42", age_limit: "All Ages", genre: "Comedy", ticket_url: "https://mountbakertheatre.com", event_url: "https://mountbakertheatre.com", description: "Stand-up comedian and former Daily Show correspondent" },
    { id: "BEL031", title: "Three for Silver", date: "2025-10-17", time: "9:00 PM", venue: "Wild Buffalo", address: "208 W Holly St", lat: 48.7547, lng: -122.4783, price: "$15", age_limit: "21+", genre: "Rock", ticket_url: "https://wildbuffalo.net", event_url: "https://wildbuffalo.net", description: "Local rock trio with heavy blues influences" },
    { id: "BEL032", title: "Sesame Street Live!", date: "2025-10-18", time: "2:00 PM", venue: "Mount Baker Theatre", address: "104 N Commercial St", lat: 48.7545, lng: -122.4787, price: "$25", age_limit: "All Ages", genre: "Children's", ticket_url: "https://mountbakertheatre.com", event_url: "https://mountbakertheatre.com", description: "Interactive children's show featuring beloved Sesame Street characters" },
    { id: "BEL033", title: "D.R.I.", date: "2025-10-19", time: "8:00 PM", venue: "The Shakedown", address: "1212 10th St", lat: 48.7520, lng: -122.4654, price: "$22", age_limit: "All Ages", genre: "Thrash Metal", ticket_url: "https://shakedownbellingham.com", event_url: "https://shakedownbellingham.com", description: "Legendary thrash metal and crossover pioneers" },
    { id: "BEL034", title: "Murder by Death", date: "2025-10-22", time: "8:30 PM", venue: "Wild Buffalo", address: "208 W Holly St", lat: 48.7547, lng: -122.4783, price: "$28", age_limit: "21+", genre: "Gothic Rock", ticket_url: "https://wildbuffalo.net", event_url: "https://wildbuffalo.net", description: "Indiana gothic indie rock band with theatrical flair" },
    { id: "BEL035", title: "Island Gigantism", date: "2025-10-30", time: "9:30 PM", venue: "Wild Buffalo", address: "208 W Holly St", lat: 48.7547, lng: -122.4783, price: "$12", age_limit: "21+", genre: "Rock", ticket_url: "https://wildbuffalo.net", event_url: "https://wildbuffalo.net", description: "Halloween rock show with local favorites" },
    { id: "BEL036", title: "Whalien Halloween Show", date: "2025-10-31", time: "8:00 PM", venue: "The Shakedown", address: "1212 10th St", lat: 48.7520, lng: -122.4654, price: "$15", age_limit: "All Ages", genre: "Indie Rock", ticket_url: "https://shakedownbellingham.com", event_url: "https://shakedownbellingham.com", description: "Costume-encouraged indie rock Halloween celebration" },
    { id: "BEL037", title: "BSO: The Planets", date: "2025-11-09", time: "7:30 PM", venue: "Mount Baker Theatre", address: "104 N Commercial St", lat: 48.7545, lng: -122.4787, price: "$38", age_limit: "All Ages", genre: "Classical", ticket_url: "https://bellinghamsymphony.org", event_url: "https://bellinghamsymphony.org", description: "Gustav Holst's epic orchestral masterpiece" },
    { id: "BEL038", title: "Friendship Commanders", date: "2025-11-19", time: "9:00 PM", venue: "Wild Buffalo", address: "208 W Holly St", lat: 48.7547, lng: -122.4783, price: "$18", age_limit: "21+", genre: "Punk Rock", ticket_url: "https://wildbuffalo.net", event_url: "https://wildbuffalo.net", description: "High-energy punk rock from local scene veterans" },
    { id: "BEL039", title: "BSO: Holiday Magic!", date: "2025-12-07", time: "3:00 PM", venue: "Mount Baker Theatre", address: "104 N Commercial St", lat: 48.7545, lng: -122.4787, price: "$32", age_limit: "All Ages", genre: "Classical", ticket_url: "https://bellinghamsymphony.org", event_url: "https://bellinghamsymphony.org", description: "Annual holiday concert featuring seasonal favorites" },
    { id: "BEL040", title: "Holiday Jazz at the Garden", date: "2025-12-20", time: "7:00 PM", venue: "Boundary Bay Brewery", address: "1107 Railroad Ave", lat: 48.7512, lng: -122.4923, price: "Free", age_limit: "All Ages", genre: "Jazz", ticket_url: "", event_url: "https://bbaybrewery.com", description: "Free holiday jazz performance in the beer garden" }
];

// Make events data available globally
window.eventsData = eventsData;
